### ISSUE TITLE
Relax upper bound for builds with base 4.11

### ISSUE THREAD

**Issue by mgmeier** [bergey/STL#5]
GHC 8.4.1 is out with base 4.11, please adjust package constraints.

Also, this time, please make a release on hackage; the current version 0.3.0.5 is not even published there.

**Comment by bergey** [comment]
Uploaded [0.3.0.6](https://hackage.haskell.org/package/STL-0.3.0.6).  Do either of you want commit permissions so you can fix this yourself next time?
